name: nutritionapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_auth_web: ^5.14.2

  # Needed for web support
  js: ^0.7.2

  # âœ… For Fitbit OAuth + HTTP requests
  http: ^0.13.6
  url_launcher: ^6.2.5
  uni_links: ^0.5.1

  # iOS style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
